{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- if .Values.networkPolicy.policyTypes }}
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 2 }}
  {{- else }}
  - Ingress
  - Egress
  {{- end }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
